name: 'Publish test results to Platform'
description: 'Publish test results from external tools to the CloudBees platform.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  test-type:
    description: 'Test Type indicating testing tool report that needs conversion.'
    required: true
  results-path:
    description: 'Folder name/File path for the location of the test reports.'
    required: true

runs:
  using: "docker"  
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-publish-test-results:main-e66674fc8ada74ae8b6fa859894387d1c870e039"  
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    TEST_TYPE: ${{ inputs.test-type }}
    FOLDER_PATH: ${{ inputs.results-path }}
