= Publish test results to the CloudBees platform

Use this action to publish test results if you are using a GitHub Actions (GHA) workflow.
This action supports many popular testing tools, and enables testing results from running a GHA workflow to be displayed in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/test-results[Test results] tab of *Run details* and in the link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/analytics/test-insights[Test insights] analytics dashboard.

== Prerequisites

Set up the CloudBees platform and GHA to work together, providing key features of the platform to GHA workflows.
Refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/gha-getting-started[Getting started with GHA integration] for more information.

== Inputs

[cols="22%a,15%a,15%a,48%a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `test-type`
| String
| Yes
| The name of the testing tool^[1]^.

| `results-path`
| String
| Yes
| The pattern, file, or directory path of the test report to convert.

| `cloudbees-url`
| String
| No
| The CloudBees platform URL. The default value is `"https://api.cloudbees.io"`.
|===

^[1]^ The testing tool name must be formatted correctly, in either all lowercase, or all uppercase.

== Supported testing tools

NOTE: Only the testing tools listed in the table below are supported for use in this action.

Use the given `test-type` input format to specify a testing tool.

[cols="40%a,30%a,30%a"]
.Supported testing tool names and `test-type` format
|===
h| Supported tool name
2+h| Accepted `test-type` input formats

|
| lowercase
| UPPERCASE

| GO
| `go`
| `GO`

| Jest
| `jest`
| `JEST`

| JUnit
| `junit`
| `JUNIT`

| MSTest
| `mstest`
| `MSTEST`

| Playwright
| `playwright`
| `PLAYWRIGHT`

| ProdPerfect
| `prodperfect`
| `PRODPERFECT`

| Selenium
| `selenium`
| `SELENIUM`

| TestNG
| `testng`
| `TESTNG`

| Tosca
| `tosca`
| `TOSCA`

|===

== Usage examples

=== Basic example

The following is a basic example of using the v2 action:

[source,yaml]
----
permissions:
      id-token: write
      contents: read
steps:
      - name: publish GHA run test results
        uses: cloudbees-io-gha/publish-test-results@v2
        with:
          test-type: junit
          results-path: /example-dir/my-test-results

----

=== Full workflow and run example

The following GHA workflow example uses the v2 action to publish test results to the CloudBees platform.

.Example GHA workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: GHA Workflow

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Compile code
        run: echo "Compiling..."

      - name: Produce binary
        run: sleep 10

      - name: Push binary
        run: echo "Pushing binary to ECR..."

      - name: Register Build Artifacts in Cloudbees Platform
        uses: cloudbees-io-gha/register-build-artifact@v3
        id: go-action
        with:
          name: "gha-artifact-test"
          version: 1.0.0
          url: "docker.io/example:latest"
          digest: "sha256:1234567890abcdef1234abcd1234567890121234567890abcdef12345678abcd"
          type: "docker"
          cloudbees-url: "https://api.cloudbees.io"

  test:
    runs-on: ubuntu-latest
    needs: [build]   # Depends on 'build' job
    steps:
      - name: Run tests
        run: echo "Running tests..."

      - name: Checkout to collect test results
        uses: actions/checkout@v3

      - name: Publish test results in Cloudbees platform
        uses: cloudbees-io-gha/publish-test-results@v2
        with:
          test-type: GO
          results-path: test_reports/*
          cloudbees-url: "https://api.cloudbees.io"

  deploy:
    runs-on: ubuntu-latest
    needs: [build,test]   # Depends on 'build' and 'test' jobs
    steps:
      - name: Checkout to prepare manifest
        uses: actions/checkout@v3

      - name: Trigger deployment
        run: echo "Invoking CBP deploy workflow..."
----
--

After the run has completed, the testing results are collected and displayed in the *Test results* tab of *Run details* and in the *Test insights* dashboard.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/intro[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

